## These multipliers will affect the standard given damage.
## Non-combo hits damage x1
damageMultipliers:
  combo5: 1.1
  combo10: 1.2
  combo20: 1.35
  combo50: 1.5
## Max time between hits before the combo is reseted
comboDuration: 2
## Message to show when a combo is reached
messages:
  combo5: '§c§l    >>>§r§eMulti Hit Combo (x5)§c§l<<<'
  combo10: '§c§l    >>>§r§eSuper Hit Combo (x10)§c§l<<<'
  combo20: '§c§l    >>>§r§eUltra Hit Combo (x20)§c§l<<<'
  combo50: '§c§l    >>>§r§eHyper Hit Combo (x50)§c§l<<<'