## These multipliers will affect the standard given damage.
## Non-combo hits damage x1
damageMultipliers:
  combo5: 1.1
  combo10: 1.2
  combo20: 1.35
  combo50: 1.5
## Max time between hits before the combo is reseted
comboDuration: 2
## Language. Points to the file "lang_%language%.yml"
language: "en"